services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ms-core-banco:
    image: dericesn/ms-core-banco:latest
    depends_on: [kafka]
    ports: ["8090:8090"]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    restart: unless-stopped

  bff-cajeros:
    image: dericesn/bff-cajeros:latest
    depends_on: [ms-core-banco]
    ports: ["8094:8094"]
    restart: unless-stopped

  bff-web:
    image: dericesn/bff-web:latest
    depends_on: [ms-core-banco]
    ports: ["8091:8091"]
    restart: unless-stopped

  bff-movil:
    image: dericesn/bff-movil:latest
    depends_on: [ms-core-banco]
    ports: ["8092:8092"]
    restart: unless-stopped
