spring.application.name=bffcajeros
server.port=8094

core.base-url=http://localhost:8090
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=bffcajeros

# ===== Resilience4j: Circuit Breaker para llamadas a ms-core-banco =====
# Evalua las ultimas 5 llamadas para decidir si abrir el circuito
resilience4j.circuitbreaker.instances.msCoreBanco.sliding-window-size=5
# Si el 50% de esas llamadas falla, el circuito se abre
resilience4j.circuitbreaker.instances.msCoreBanco.failure-rate-threshold=50
# Tiempo que el circuito queda abierto antes de probar de nuevo (half-open)
resilience4j.circuitbreaker.instances.msCoreBanco.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.msCoreBanco.permitted-number-of-calls-in-half-open-state=2
# Los 4xx (saldo insuficiente, cuenta no existe) son errores de NEGOCIO, no fallas del servicio,
# por eso no deben contar para abrir el circuito
resilience4j.circuitbreaker.instances.msCoreBanco.ignore-exceptions=org.springframework.web.client.HttpClientErrorException

# ===== Resilience4j: Retry para llamadas a ms-core-banco =====
resilience4j.circuitbreaker.instances.msCoreBanco.minimum-number-of-calls=5
resilience4j.retry.instances.msCoreBanco.ignore-exceptions=org.springframework.web.client.HttpClientErrorException,io.github.resilience4j.circuitbreaker.CallNotPermittedException

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=bff-cajeros
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# Clave secreta para firmar/verificar JWT (mínimo 32 caracteres)
jwt.secret-key=MiClaveSuperSecretaBancariaParaTokensOAuth2026DuocUC