spring.application.name=bffcajeros
server.port=8094

# En docker-compose se sobreescribe con http://ms-core-banco:8090
core.base-url=${CORE_BASE_URL:http://localhost:8090}
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=bffcajeros

# ===== Resilience4j: Circuit Breaker para llamadas a ms-core-banco =====
# Evalua las ultimas 5 llamadas para decidir si abrir el circuito
resilience4j.circuitbreaker.instances.msCoreBanco.sliding-window-size=5
# Si el 50% de esas llamadas falla, el circuito se abre
resilience4j.circuitbreaker.instances.msCoreBanco.failure-rate-threshold=50
# Tiempo que el circuito queda abierto antes de probar de nuevo (half-open)
resilience4j.circuitbreaker.instances.msCoreBanco.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.msCoreBanco.permitted-number-of-calls-in-half-open-state=2
# Los 4xx (saldo insuficiente, cuenta no existe) son errores de NEGOCIO, no fallas del servicio,
# por eso no deben contar para abrir el circuito
resilience4j.circuitbreaker.instances.msCoreBanco.ignore-exceptions=org.springframework.web.client.HttpClientErrorException

# ===== Resilience4j: Retry para llamadas a ms-core-banco =====
resilience4j.circuitbreaker.instances.msCoreBanco.minimum-number-of-calls=5
resilience4j.retry.instances.msCoreBanco.ignore-exceptions=org.springframework.web.client.HttpClientErrorException,io.github.resilience4j.circuitbreaker.CallNotPermittedException

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=bff-cajeros
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# ===== OAuth2.0 (reemplaza Basic Auth) =====
# URLs de auth-server (en docker-compose se sobreescriben con http://auth-server:9000/...)
auth.jwks-uri=${AUTH_JWKS_URI:http://localhost:9000/oauth2/jwks}
auth.token-uri=${AUTH_TOKEN_URI:http://localhost:9000/oauth2/token}

# 1) Resource Server: valida los JWT que llegan desde los cajeros
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${auth.jwks-uri}

# 2) Cliente OAuth2: este BFF pide su propio token (client_credentials) para llamar a ms-core-banco
spring.security.oauth2.client.provider.authserver.token-uri=${auth.token-uri}
spring.security.oauth2.client.registration.core.provider=authserver
spring.security.oauth2.client.registration.core.client-id=bff-cajeros-service
spring.security.oauth2.client.registration.core.client-secret=${BFF_CAJEROS_SERVICE_SECRET:cajerossvc123}
spring.security.oauth2.client.registration.core.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.core.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.core.scope=core.read,core.write
